
CC_PATH=/home/ubuntu/corn/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.3.0_musl/bin
CC_TOOL=mips-openwrt-linux-gcc-7.3.0
send_data: sendData.c		
	$(CC_PATH)/$(CC_TOOL) -o send_data sendData.c

clean: 
	rm -f *.o senddata

